# AUTOGENERATED! DO NOT EDIT! File to edit: 02_app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image_widget', 'label_widget', 'examples', 'intf', 'is_cat', 'classify_image']

# %% 02_app.ipynb 3
from fastai.vision.all import *
import gradio


def is_cat(x):
    return x[0].isupper()


# %% 02_app.ipynb 5
learn = load_learner("02_is_cat_model.pkl")


# %% 02_app.ipynb 7
categories = ("Dog", "Cat")

def classify_image(img):
    pred, idx, probs = learn.predict(img)
    return dict(zip(categories, [float(prob) for prob in probs]))

# %% 02_app.ipynb 9
image_widget = gradio.Image(height=192, width=192)
label_widget = gradio.Label()

examples = ["dog.jpg", "cat.jpg", "dunno.jpg"]

intf = gradio.Interface(fn=classify_image, inputs=image_widget, outputs=label_widget, examples=examples)

# %% 02_app.ipynb 12
intf.launch(inline=False)
